name: Sync
on: 
    schedule:
      - cron:  '0 0 * * 0'
    workflow_dispatch:

jobs:
    sync:
        name: Sync
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Checkout GitLab
              run: |
                git remote add gl https://gitlab.com/An0/SimpleDiscordCrypt.git
                git pull gl master:gitlab-sync || true
                git checkout gitlab-sync
                git remote remove gl
            - name: create pull request
              run: |
                git push --set-upstream origin gitlab-sync
                git push origin
                gh pr create -B master -H gitlab-sync --title 'Merge GitLab changes' --body 'Automatic PR'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          